version: '3.3'
services:
  nginx:
    restart: always
    image: nginx:latest
    links:
      - web:web
    ports:
      - "8060:8060"
    volumes:
      - ./utility/nginx.default.conf:/etc/nginx/conf.d/nginx.default.conf
  web:
    build: .
    restart: always
    command: bash -c "/env/bin/gunicorn application:app --bind :8000"
    #command: bash -c "/env/bin/python -u run.py"
    volumes:
      - ./application:/application
      - ./config:/config
      #- ./run.py:/run.py
    environment:
      - ALVEO_API_KEY=
      - ALVEO_API_URL=https://staging.alveo.edu.au/
    expose:
      - "8000"
